import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Geist_Mono, Inter, Playfair_Display } from 'next/font/google';
import Navbar from '../components/shared/main-navbar';
import MobileTabBar from '../components/shared/mobile-tab-bar';
import './globals.css';
import Providers from './providers';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const playfairDisplay = Playfair_Display({
  variable: '--font-display-serif',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'TenantShield',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${inter.variable} ${playfairDisplay.variable} ${geistMono.variable} antialiased`}>
      <body>
        <ClerkProvider>
          <Providers>
            <Navbar />
            {children}
            <MobileTabBar />
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
